// import forms from '@tailwindcss/forms'
import typography from '@tailwindcss/typography'

export default {
    content: ['./resources/views/**/*.blade.php'],
    theme: {
        extend: {
            colors: {
                custom: {
                    50: 'rgba(var(--custom-50), <alpha-value>)',
                    100: 'rgba(var(--custom-100), <alpha-value>)',
                    200: 'rgba(var(--custom-200), <alpha-value>)',
                    300: 'rgba(var(--custom-300), <alpha-value>)',
                    400: 'rgba(var(--custom-400), <alpha-value>)',
                    500: 'rgba(var(--custom-500), <alpha-value>)',
                    600: 'rgba(var(--custom-600), <alpha-value>)',
                    700: 'rgba(var(--custom-700), <alpha-value>)',
                    800: 'rgba(var(--custom-800), <alpha-value>)',
                    900: 'rgba(var(--custom-900), <alpha-value>)',
                    950: 'rgba(var(--custom-950), <alpha-value>)',
                },
                primary: {
                    50: 'rgba(var(--primary-50), <alpha-value>)',
                    100: 'rgba(var(--primary-100), <alpha-value>)',
                    200: 'rgba(var(--primary-200), <alpha-value>)',
                    300: 'rgba(var(--primary-300), <alpha-value>)',
                    400: 'rgba(var(--primary-400), <alpha-value>)',
                    500: 'rgba(var(--primary-500), <alpha-value>)',
                    600: 'rgba(var(--primary-600), <alpha-value>)',
                    700: 'rgba(var(--primary-700), <alpha-value>)',
                    800: 'rgba(var(--primary-800), <alpha-value>)',
                    900: 'rgba(var(--primary-900), <alpha-value>)',
                    950: 'rgba(var(--primary-950), <alpha-value>)',
                },
                secondary: {
                    50: 'rgba(var(--secondary-50), <alpha-value>)',
                    100: 'rgba(var(--secondary-100), <alpha-value>)',
                    200: 'rgba(var(--secondary-200), <alpha-value>)',
                    300: 'rgba(var(--secondary-300), <alpha-value>)',
                    400: 'rgba(var(--secondary-400), <alpha-value>)',
                    500: 'rgba(var(--secondary-500), <alpha-value>)',
                    600: 'rgba(var(--secondary-600), <alpha-value>)',
                    700: 'rgba(var(--secondary-700), <alpha-value>)',
                    800: 'rgba(var(--secondary-800), <alpha-value>)',
                    900: 'rgba(var(--secondary-900), <alpha-value>)',
                    950: 'rgba(var(--secondary-950), <alpha-value>)',
                },
                danger: {
                    50: 'rgba(var(--danger-50), <alpha-value>)',
                    100: 'rgba(var(--danger-100), <alpha-value>)',
                    200: 'rgba(var(--danger-200), <alpha-value>)',
                    300: 'rgba(var(--danger-300), <alpha-value>)',
                    400: 'rgba(var(--danger-400), <alpha-value>)',
                    500: 'rgba(var(--danger-500), <alpha-value>)',
                    600: 'rgba(var(--danger-600), <alpha-value>)',
                    700: 'rgba(var(--danger-700), <alpha-value>)',
                    800: 'rgba(var(--danger-800), <alpha-value>)',
                    900: 'rgba(var(--danger-900), <alpha-value>)',
                    950: 'rgba(var(--danger-950), <alpha-value>)',
                },
                info: {
                    50: 'rgba(var(--info-50), <alpha-value>)',
                    100: 'rgba(var(--info-100), <alpha-value>)',
                    200: 'rgba(var(--info-200), <alpha-value>)',
                    300: 'rgba(var(--info-300), <alpha-value>)',
                    400: 'rgba(var(--info-400), <alpha-value>)',
                    500: 'rgba(var(--info-500), <alpha-value>)',
                    600: 'rgba(var(--info-600), <alpha-value>)',
                    700: 'rgba(var(--info-700), <alpha-value>)',
                    800: 'rgba(var(--info-800), <alpha-value>)',
                    900: 'rgba(var(--info-900), <alpha-value>)',
                    950: 'rgba(var(--info-950), <alpha-value>)',
                },
                success: {
                    50: 'rgba(var(--success-50), <alpha-value>)',
                    100: 'rgba(var(--success-100), <alpha-value>)',
                    200: 'rgba(var(--success-200), <alpha-value>)',
                    300: 'rgba(var(--success-300), <alpha-value>)',
                    400: 'rgba(var(--success-400), <alpha-value>)',
                    500: 'rgba(var(--success-500), <alpha-value>)',
                    600: 'rgba(var(--success-600), <alpha-value>)',
                    700: 'rgba(var(--success-700), <alpha-value>)',
                    800: 'rgba(var(--success-800), <alpha-value>)',
                    900: 'rgba(var(--success-900), <alpha-value>)',
                    950: 'rgba(var(--success-950), <alpha-value>)',
                },
                warning: {
                    50: 'rgba(var(--warning-50), <alpha-value>)',
                    100: 'rgba(var(--warning-100), <alpha-value>)',
                    200: 'rgba(var(--warning-200), <alpha-value>)',
                    300: 'rgba(var(--warning-300), <alpha-value>)',
                    400: 'rgba(var(--warning-400), <alpha-value>)',
                    500: 'rgba(var(--warning-500), <alpha-value>)',
                    600: 'rgba(var(--warning-600), <alpha-value>)',
                    700: 'rgba(var(--warning-700), <alpha-value>)',
                    800: 'rgba(var(--warning-800), <alpha-value>)',
                    900: 'rgba(var(--warning-900), <alpha-value>)',
                    950: 'rgba(var(--warning-950), <alpha-value>)',
                },
                light: {
                    50: 'rgba(var(--light-50), <alpha-value>)',
                    100: 'rgba(var(--light-100), <alpha-value>)',
                    200: 'rgba(var(--light-200), <alpha-value>)',
                    300: 'rgba(var(--light-300), <alpha-value>)',
                    400: 'rgba(var(--light-400), <alpha-value>)',
                    500: 'rgba(var(--light-500), <alpha-value>)',
                    600: 'rgba(var(--light-600), <alpha-value>)',
                    700: 'rgba(var(--light-700), <alpha-value>)',
                    800: 'rgba(var(--light-800), <alpha-value>)',
                    900: 'rgba(var(--light-900), <alpha-value>)',
                    950: 'rgba(var(--light-950), <alpha-value>)',
                },
                dark: {
                    50: 'rgba(var(--dark-50), <alpha-value>)',
                    100: 'rgba(var(--dark-100), <alpha-value>)',
                    200: 'rgba(var(--dark-200), <alpha-value>)',
                    300: 'rgba(var(--dark-300), <alpha-value>)',
                    400: 'rgba(var(--dark-400), <alpha-value>)',
                    500: 'rgba(var(--dark-500), <alpha-value>)',
                    600: 'rgba(var(--dark-600), <alpha-value>)',
                    700: 'rgba(var(--dark-700), <alpha-value>)',
                    800: 'rgba(var(--dark-800), <alpha-value>)',
                    900: 'rgba(var(--dark-900), <alpha-value>)',
                    950: 'rgba(var(--dark-950), <alpha-value>)',
                },
                gray: {
                    50: 'rgba(var(--gray-50), <alpha-value>)',
                    100: 'rgba(var(--gray-100), <alpha-value>)',
                    200: 'rgba(var(--gray-200), <alpha-value>)',
                    300: 'rgba(var(--gray-300), <alpha-value>)',
                    400: 'rgba(var(--gray-400), <alpha-value>)',
                    500: 'rgba(var(--gray-500), <alpha-value>)',
                    600: 'rgba(var(--gray-600), <alpha-value>)',
                    700: 'rgba(var(--gray-700), <alpha-value>)',
                    800: 'rgba(var(--gray-800), <alpha-value>)',
                    900: 'rgba(var(--gray-900), <alpha-value>)',
                    950: 'rgba(var(--gray-950), <alpha-value>)',
                },
                red: {
                    50: 'rgba(var(--red-50), <alpha-value>)',
                    100: 'rgba(var(--red-100), <alpha-value>)',
                    200: 'rgba(var(--red-200), <alpha-value>)',
                    300: 'rgba(var(--red-300), <alpha-value>)',
                    400: 'rgba(var(--red-400), <alpha-value>)',
                    500: 'rgba(var(--red-500), <alpha-value>)',
                    600: 'rgba(var(--red-600), <alpha-value>)',
                    700: 'rgba(var(--red-700), <alpha-value>)',
                    800: 'rgba(var(--red-800), <alpha-value>)',
                    900: 'rgba(var(--red-900), <alpha-value>)',
                    950: 'rgba(var(--red-950), <alpha-value>)',
                },
            },
        },
    },
    plugins: [forms, typography],
}
